services:
  - type: web
    name: testTask
    runtime: docker
    repo: https://github.com/Leshka290/testTask.git
    rootDir: testTask
    branch: master
    healthCheckPath: /
databases:
  - name: postgres
    user: postgres